# Generated by Django 3.2.5 on 2022-03-25 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blindbox',
            fields=[
                ('boxid', models.IntegerField(db_column='boxID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('b_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'blindbox',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cardno', models.IntegerField(db_column='cardNO', primary_key=True, serialize=False)),
                ('rarity', models.CharField(max_length=50)),
                ('c_name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'card',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ownedcard',
            fields=[
                ('cardid', models.IntegerField(db_column='cardID', primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('c_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cardno', models.ForeignKey(db_column='cardNO', on_delete=django.db.models.deletion.CASCADE, to='Pokemon.card')),
            ],
            options={
                'db_table': 'ownedcard',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(db_column='userID', primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('u_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resaleorder',
            fields=[
                ('r_orderid', models.IntegerField(db_column='r_orderID', primary_key=True, serialize=False)),
                ('trade_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trade_datetime', models.CharField(max_length=50)),
                ('buyerid', models.ForeignKey(db_column='buyerID', on_delete=django.db.models.deletion.CASCADE, related_name='buyerid', to='Pokemon.user')),
                ('cardid', models.ForeignKey(db_column='cardID', on_delete=django.db.models.deletion.CASCADE, to='Pokemon.ownedcard')),
                ('sellerid', models.ForeignKey(db_column='sellerID', on_delete=django.db.models.deletion.CASCADE, related_name='sellerid', to='Pokemon.user')),
            ],
            options={
                'db_table': 'resaleorder',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Probability',
            fields=[
                ('ruleno', models.IntegerField(db_column='ruleNO', primary_key=True, serialize=False)),
                ('rarity', models.CharField(max_length=50)),
                ('prob', models.DecimalField(decimal_places=3, max_digits=10)),
                ('boxid', models.ForeignKey(db_column='boxID', on_delete=django.db.models.deletion.CASCADE, to='Pokemon.blindbox')),
            ],
            options={
                'db_table': 'probability',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ownedcard',
            name='userid',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='Pokemon.user'),
        ),
        migrations.CreateModel(
            name='Boxorder',
            fields=[
                ('b_orderid', models.IntegerField(db_column='b_orderID', primary_key=True, serialize=False)),
                ('pay_datetime', models.CharField(max_length=50)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boxid', models.ForeignKey(db_column='boxID', on_delete=django.db.models.deletion.CASCADE, to='Pokemon.blindbox')),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='Pokemon.user')),
            ],
            options={
                'db_table': 'boxorder',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contain',
            fields=[
                ('cardno', models.OneToOneField(db_column='cardNO', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Pokemon.card')),
                ('boxid', models.ForeignKey(db_column='boxID', on_delete=django.db.models.deletion.CASCADE, to='Pokemon.blindbox')),
            ],
            options={
                'db_table': 'contain',
                'managed': True,
                'unique_together': {('cardno', 'boxid')},
            },
        ),
    ]
