# Generated by Django 3.2.5 on 2022-03-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokemon', '0003_alter_user_u_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.AutoField(db_column='userID', primary_key=True, serialize=False),
        ),
    ]
