# Generated by Django 3.2.5 on 2022-03-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokemon', '0004_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindbox',
            name='boxid',
            field=models.AutoField(db_column='boxID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='boxorder',
            name='b_orderid',
            field=models.AutoField(db_column='b_orderID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardno',
            field=models.AutoField(db_column='cardNO', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ownedcard',
            name='cardid',
            field=models.AutoField(db_column='cardID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='probability',
            name='ruleno',
            field=models.AutoField(db_column='ruleNO', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resaleorder',
            name='r_orderid',
            field=models.AutoField(db_column='r_orderID', primary_key=True, serialize=False),
        ),
    ]
